### ISSUE TITLE
this.$ga.event not working

### ISSUE THREAD

**Issue by croossin** [MatteoGabriele/vue-analytics#137]
If you are reporting a bug, please fill in below. Otherwise feel free to remove this template entirely.

### Description

I can not seem to get the event to report to the GA dashboard

### Expected behavior

Events reported to GA dashboard

### Actual behavior

No events being reported

### Environment

`vue-analytics@5.12.2`

Then, specify:

1. Operating system:
MacOS 10.13.5

2. Browser and version:
Version 67.0.3396.99 (Official Build) (64-bit)

### Reproducible Demo

In `main.js`:
```
Vue.use(VueAnalytics, {
  id: 'UA-XXXXXXX', // Have valid code - just removing for GitHub issue
  router,
  debug: {
    sendHitTask: process.env.NODE_ENV === 'production'
  },
  commands: {
    trackClick (category, label, value) {
        this.$ga.event({
          eventCategory: category,
          eventAction: 'click',
          eventLabel: label,
          eventValue: value
        })
    }
  }
})
```

In any `.vue` file:
```html
<a v-ga="$ga.commands.trackClick.bind(this, 'tile', 'title', story.storyLink)" :href="story.storyLink" target="_blank">{{ story.title }}</a>
```

I know it is hitting that function because when I `console.log` inside it prints when I expect it to.  I also removed the debug `sendHitTask` to ensure it was nothing to do with env variable.

**Comment by croossin** [comment]
Fixed :D

**Comment by Jarzka** [comment]
I have the same problem. How was it fixed?

**Comment by reneecampanilla** [comment]
I had the same problem. I fixed it by adding trackEvent and set it to true.

`Vue.use(VueAnalytics, {
  id: 'UA-128771822-1',
  trackEvent: true
});`

It displays in the Real Time >> Events page now.

**Comment by mrodrig** [comment]
I was running into an issue with getting events working and figured I'd post here with what my issue was in case it helps someone else down the road... I was sending a string for the `value` field, but per Google Analytic's help docs, the `value` must be an integer (https://support.google.com/analytics/answer/1033068?hl=en  - scroll down to the Value section). When sending a String, I wasn't seeing any events getting logged until I removed the value the event data that I was sending. Hopefully this helps someone!

**Comment by jcfinnerup** [comment]
> I was running into an issue with getting events working and figured I'd post here with what my issue was in case it helps someone else down the road... I was sending a string for the `value` field, but per Google Analytic's help docs, the `value` must be an integer (https://support.google.com/analytics/answer/1033068?hl=en - scroll down to the Value section). When sending a String, I wasn't seeing any events getting logged until I removed the value the event data that I was sending. Hopefully this helps someone!

Thanks! I had the same issue, but it wasn't fixed until i did both of the suggestions above. 
So 1. removed the "string" value and replaced it with an Integer and 2. set `trackEvent: true`
